### ISSUE TITLE
Fix for Cookie Deletion Issue in eraseCookie Method

### ISSUE THREAD

**Issue by raulmelo** [murafalizade/react-vite-ts-tlw-template#1]
I encountered a problem in eraseCookie method where cookies were not being deleted as expected. This issue was persistent across different browsers and environments.

**Root Cause:**
Upon further investigation, I discovered that the eraseCookie method was not specifying the path when attempting to delete the cookie. In our setCookie method, we set cookies with the path=/ attribute, making them available across the entire domain. However, when trying to erase these cookies without specifying the same path, the deletion was unsuccessful.

**Solution:**
To address this inconsistency, I've updated the eraseCookie method to include path=/ in the cookie deletion process. This change ensures that the cookie deletion aligns with how we initially set them.

**Updated eraseCookie Method:**

```
public static eraseCookie(name: string) {
    document.cookie = name + '=; Max-Age=-99999999; path=/;';
}
```

**Comment by raulmelo** [comment]
Pull request suggestion: 
https://github.com/murafalizade/react-vite-ts-tlw-template/compare/main...raulmelo:react-vite-ts-tlw-template:patch-1

**Comment by murafalizade** [comment]
Thank you for such a great investigation and solution. You are right, I pulled and merged your solution.
